<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Recepcion\Clasificacion;

class ClasificacionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clasificaciones = [
            [1, '2000 Materiales y Suministros', 'Agrupa las asignaciones para la adquisición de insumos y suministros requeridos para la prestación de servicios y actividades administrativas.'],
            [2, '2100 Materiales de Administración, Emisión de Documentos y Artículos Oficiales', 'Materiales de Administración, Emisión de Documentos y Artículos Oficiales'],
            [3, '2111 Materiales, útiles y equipos menores de oficina', 'Materiales, útiles y equipos menores de oficina'],
            [4, '2121 Materiales y útiles de impresión y reproducción', 'Materiales y útiles de impresión y reproducción'],
            [5, '2131 Material estadístico y geográfico', 'Material estadístico y geográfico'],
            [6, '2141 Materiales, útiles y equipos menores de tecnologías de la información y comunicaciones', 'Materiales, útiles y equipos menores de tecnologías de la información y comunicaciones'],
            [7, '2151 Material impreso e información digital', 'Material impreso e información digital'],
            [8, '2161 Material de limpieza', 'Material de limpieza'],
            [9, '2171 Materiales y útiles de enseñanza', 'Materiales y útiles de enseñanza'],
            [10, '2181 Materiales para el registro e identificación de bienes y personas', 'Materiales para el registro e identificación de bienes y personas'],
            [11, '2200 Alimentos y Utensilios', 'Alimentos y Utensilios'],
            [12, '2211 Productos alimenticios para personas', 'Productos alimenticios para personas'],
            [13, '2221 Productos alimenticios para animales', 'Productos alimenticios para animales'],
            [14, '2231 Utensilios para el servicio de alimentación', 'Utensilios para el servicio de alimentación'],
            [15, '2300 Materias Primas y Materiales de Producción y Comercialización', 'Materias Primas y Materiales de Producción y Comercialización'],
            [16, '2311 Productos alimenticios, agropecuarios y forestales adquiridos como materia prima', 'Productos alimenticios, agropecuarios y forestales adquiridos como materia prima'],
            [17, '2321 Insumos textiles adquiridos como materia prima', 'Insumos textiles adquiridos como materia prima'],
            [18, '2331 Productos de papel, cartón e impresos adquiridos como materia prima', 'Productos de papel, cartón e impresos adquiridos como materia prima'],
            [19, '2341 Combustibles, lubricantes, aditivos, carbón y sus derivados adquiridos como materia prima', 'Combustibles, lubricantes, aditivos, carbón y sus derivados adquiridos como materia prima'],
            [20, '2351 Productos químicos, farmacéuticos y de laboratorio adquiridos como materia prima', 'Productos químicos, farmacéuticos y de laboratorio adquiridos como materia prima'],
            [21, '2361 Productos metálicos y a base de minerales no metálicos adquiridos como materia prima', 'Productos metálicos y a base de minerales no metálicos adquiridos como materia prima'],
            [22, '2371 Productos de cuero, piel, plástico y hule adquiridos como materia prima', 'Productos de cuero, piel, plástico y hule adquiridos como materia prima'],
            [23, '2381 Mercancías adquiridas para su comercialización', 'Mercancías adquiridas para su comercialización'],
            [24, '2391 Otros productos adquiridos como materia prima', 'Otros productos adquiridos como materia prima'],
            [25, '2400 Materiales y Artículos de Construcción y de Reparación', 'Materiales y Artículos de Construcción y de Reparación'],
            [26, '2411 Productos minerales no metálicos', 'Productos minerales no metálicos'],
            [27, '2421 Cemento y productos de concreto', 'Cemento y productos de concreto'],
            [28, '2431 Cal, yeso y productos de yeso', 'Cal, yeso y productos de yeso'],
            [29, '2441 Madera y productos de madera', 'Madera y productos de madera'],
            [30, '2451 Vidrio y productos de vidrio', 'Vidrio y productos de vidrio'],
            [31, '2461 Material eléctrico y electrónico', 'Material eléctrico y electrónico'],
            [32, '2471 Artículos metálicos para la construcción', 'Artículos metálicos para la construcción'],
            [33, '2481 Materiales complementarios', 'Materiales complementarios'],
            [34, '2491 Otros materiales y artículos de construcción y reparación', 'Otros materiales y artículos de construcción y reparación'],
            [35, '2500 Productos Químicos, Farmacéuticos y de Laboratorio', 'Productos Químicos, Farmacéuticos y de Laboratorio'],
            [36, '2511 Productos químicos básicos', 'Productos químicos básicos'],
            [37, '2521 Fertilizantes, pesticidas y otros agroquímicos', 'Fertilizantes, pesticidas y otros agroquímicos'],
            [38, '2531 Medicinas y productos farmacéuticos', 'Medicinas y productos farmacéuticos'],
            [39, '2541 Materiales, accesorios y suministros médicos', 'Materiales, accesorios y suministros médicos'],
            [40, '2551 Materiales, accesorios y suministros de laboratorio', 'Materiales, accesorios y suministros de laboratorio'],
            [41, '2561 Fibras sintéticas, hules, plásticos y derivados', 'Fibras sintéticas, hules, plásticos y derivados'],
            [42, '2591 Otros productos químicos', 'Otros productos químicos'],
            [43, '2600 Combustibles, Lubricantes y Aditivos', 'Combustibles, Lubricantes y Aditivos'],
            [44, '2611 Combustibles, lubricantes y aditivos', 'Combustibles, lubricantes y aditivos'],
            [45, '2621 Carbón y sus derivados', 'Carbón y sus derivados'],
            [46, '2700 Vestuario, Blancos, Prendas de Protección y Artículos Deportivos', 'Vestuario, Blancos, Prendas de Protección y Artículos Deportivos'],
            [47, '2711 Vestuario y uniformes', 'Vestuario y uniformes'],
            [48, '2721 Prendas de seguridad y protección personal', 'Prendas de seguridad y protección personal'],
            [49, '2731 Artículos deportivos', 'Artículos deportivos'],
            [50, '2741 Productos textiles', 'Productos textiles'],
            [51, '2751 Blancos y otros productos textiles, excepto prendas de vestir', 'Blancos y otros productos textiles, excepto prendas de vestir'],
            [52, '2800 Materiales y Suministros para Seguridad', 'Materiales y Suministros para Seguridad'],
            [53, '2811 Sustancias y materiales explosivos', 'Sustancias y materiales explosivos'],
            [54, '2821 Materiales de seguridad pública', 'Materiales de seguridad pública'],
            [55, '2831 Prendas de protección para seguridad pública y nacional', 'Prendas de protección para seguridad pública y nacional'],
            [56, '2900 Herramientas, Refacciones y Accesorios Menores', 'Herramientas, Refacciones y Accesorios Menores'],
            [57, '2911 Herramientas menores', 'Herramientas menores'],
            [58, '2921 Refacciones y accesorios menores de edificios', 'Refacciones y accesorios menores de edificios'],
            [59, '2931 Refacciones y accesorios menores de mobiliario y equipo de administración, educacional y recreativo', 'Refacciones y accesorios menores de mobiliario y equipo de administración, educacional y recreativo'],
            [60, '2941 Refacciones y accesorios menores de equipo de cómputo y tecnologías de la información', 'Refacciones y accesorios menores de equipo de cómputo y tecnologías de la información'],
            [61, '2951 Refacciones y accesorios menores de equipo e instrumental médico y de laboratorio', 'Refacciones y accesorios menores de equipo e instrumental médico y de laboratorio'],
            [62, '2961 Refacciones y accesorios menores de equipo de transporte', 'Refacciones y accesorios menores de equipo de transporte'],
            [63, '2971 Refacciones y accesorios menores de equipo de defensa y seguridad', 'Refacciones y accesorios menores de equipo de defensa y seguridad'],
            [64, '2981 Refacciones y accesorios menores de maquinaria y otros equipos', 'Refacciones y accesorios menores de maquinaria y otros equipos'],
            [65, '2991 Refacciones y accesorios menores otros bienes muebles', 'Refacciones y accesorios menores otros bienes muebles'],
            [66, '3000 Servicios Generales', 'Asignaciones destinadas a cubrir el costo de servicios contratados con particulares o instituciones del sector público.'],
            [67, '3100 Servicios Básicos', 'Servicios Básicos'],
            [68, '3111 Energía eléctrica', 'Energía eléctrica'],
            [69, '3121 Gas', 'Gas'],
            [70, '3131 Agua', 'Agua'],
            [71, '3141 Telefonía tradicional', 'Telefonía tradicional'],
            [72, '3151 Telefonía celular', 'Telefonía celular'],
            [73, '3161 Servicios de telecomunicaciones y satélites', 'Servicios de telecomunicaciones y satélites'],
            [74, '3171 Servicios de acceso de Internet, redes y procesamiento de información', 'Servicios de acceso de Internet, redes y procesamiento de información'],
            [75, '3181 Servicios postales y telegráficos', 'Servicios postales y telegráficos'],
            [76, '3191 Servicios integrales y otros servicios', 'Servicios integrales y otros servicios'],
            [77, '3200 Servicios de Arrendamiento', 'Servicios de Arrendamiento'],
            [78, '3211 Arrendamiento de terrenos', 'Arrendamiento de terrenos'],
            [79, '3221 Arrendamiento de edificios', 'Arrendamiento de edificios'],
            [80, '3231 Arrendamiento de mobiliario y equipo de administración, educacional y recreativo', 'Arrendamiento de mobiliario y equipo de administración, educacional y recreativo'],
            [81, '3241 Arrendamiento de equipo e instrumental médico y de laboratorio', 'Arrendamiento de equipo e instrumental médico y de laboratorio'],
            [82, '3251 Arrendamiento de equipo de transporte', 'Arrendamiento de equipo de transporte'],
            [83, '3261 Arrendamiento de maquinaria, otros equipos y herramientas', 'Arrendamiento de maquinaria, otros equipos y herramientas'],
            [84, '3271 Arrendamiento de activos intangibles', 'Arrendamiento de activos intangibles'],
            [85, '3281 Arrendamiento financiero', 'Arrendamiento financiero'],
            [86, '3291 Otros arrendamientos', 'Otros arrendamientos'],
            [87, '3300 Servicios Profesionales, Científicos, Técnicos y Otros Servicios', 'Servicios Profesionales, Científicos, Técnicos y Otros Servicios'],
            [88, '3311 Servicios legales, de contabilidad, auditoría y relacionados', 'Servicios legales, de contabilidad, auditoría y relacionados'],
            [89, '3321 Servicios de diseño, architecture, ingeniería y actividades relacionadas', 'Servicios de diseño, architecture, ingeniería y actividades relacionadas'],
            [90, '3331 Servicios de consultoría administrativa, procesos, técnica y en tecnologías de la información', 'Servicios de consultoría administrativa, procesos, técnica y en tecnologías de la información'],
            [91, '3341 Servicios de capacitación', 'Servicios de capacitación'],
            [92, '3351 Servicios de investigación científica y desarrollo', 'Servicios de investigación científica y desarrollo'],
            [93, '3361 Servicios de apoyo administrativo, traducción, fotocopiado e impresión', 'Servicios de apoyo administrativo, traducción, fotocopiado e impresión'],
            [94, '3371 Servicios de protección y seguridad', 'Servicios de protección y seguridad'],
            [95, '3381 Servicios de vigilancia', 'Servicios de vigilancia'],
            [96, '3391 Servicios profesionales, científicos y técnicos integrales', 'Servicios profesionales, científicos y técnicos integrales'],
            [97, '3400 Servicios Financieros, Bancarios y Comerciales', 'Servicios Financieros, Bancarios y Comerciales'],
            [98, '3411 Servicios financieros y bancarios', 'Servicios financieros y bancarios'],
            [99, '3421 Servicios de cobranza, investigación crediticia y similar', 'Servicios de cobranza, investigación crediticia y similar'],
            [100, '3431 Servicios de recaudación, traslado y custodia de valores', 'Servicios de recaudación, traslado y custodia de valores'],
            [101, '3441 Seguros de responsabilidad patrimonial y fianzas', 'Seguros de responsabilidad patrimonial y fianzas'],
            [102, '3451 Seguro de bienes patrimoniales', 'Seguro de bienes patrimoniales'],
            [103, '3461 Almacenaje, envase y embalaje', 'Almacenaje, envase y embalaje'],
            [104, '3471 Fletes y maniobras', 'Fletes y maniobras'],
            [105, '3481 Comisiones por ventas', 'Comisiones por ventas'],
            [106, '3491 Servicios financieros, bancarios y comerciales integrales', 'Servicios financieros, bancarios y comerciales integrales'],
            [107, '3500 Servicios de Instalación, Reparación, Mantenimiento y Conservación', 'Servicios de Instalación, Reparación, Mantenimiento y Conservación'],
            [108, '3511 Conservación y mantenimiento menor de inmuebles', 'Conservación y mantenimiento menor de inmuebles'],
            [109, '3521 Instalación, reparación y mantenimiento de mobiliario y equipo de administración, educacional y recreativo', 'Instalación, reparación y mantenimiento de mobiliario y equipo de administración, educacional y recreativo'],
            [110, '3531 Instalación, reparación y mantenimiento de equipo de cómputo y tecnología de la información', 'Instalación, reparación y mantenimiento de equipo de cómputo y tecnología de la información'],
            [111, '3541 Instalación, reparación y mantenimiento de equipo e instrumental médico y de laboratorio', 'Instalación, reparación y mantenimiento de equipo e instrumental médico y de laboratorio'],
            [112, '3551 Reparación y mantenimiento de equipo de transporte', 'Reparación y mantenimiento de equipo de transporte'],
            [113, '3561 Reparación y mantenimiento de equipo de defensa y seguridad', 'Reparación y mantenimiento de equipo de defensa y seguridad'],
            [114, '3571 Instalación, reparación y mantenimiento de maquinaria, otros equipos y herramienta', 'Instalación, reparación y mantenimiento de maquinaria, otros equipos y herramienta'],
            [115, '3581 Servicios de limpieza y manejo de desechos', 'Servicios de limpieza y manejo de desechos'],
            [116, '3591 Servicios de jardinería y fumigación', 'Servicios de jardinería y fumigación'],
            [117, '3600 Servicios de Comunicación Social y Publicidad', 'Servicios de Comunicación Social y Publicidad'],
            [118, '3611 Difusión de mensajes sobre programas y actividades gubernamentales', 'Difusión de mensajes sobre programas y actividades gubernamentales'],
            [119, '3621 Difusión de mensajes comerciales para promover la venta de bienes o servicios', 'Difusión de mensajes comerciales para promover la venta de bienes o servicios'],
            [120, '3631 Servicios de creatividad, preproducción y producción de publicidad, excepto Internet', 'Servicios de creatividad, preproducción y producción de publicidad, excepto Internet'],
            [121, '3641 Servicios de revelado de fotografías', 'Servicios de revelado de fotografías'],
            [122, '3651 Servicios de la industria fílmica, del sonido y del video', 'Servicios de la industria fílmica, del sonido y del video'],
            [123, '3661 Servicio de creación y difusión de contenido exclusivamente a través de Internet', 'Servicio de creación y difusión de contenido exclusivamente a través de Internet'],
            [124, '3691 Otros servicios de información', 'Otros servicios de información'],
            [125, '3700 Servicios de Traslado y Viáticos', 'Servicios de Traslado y Viáticos'],
            [126, '3711 Pasajes aéreos', 'Pasajes aéreos'],
            [127, '3721 Pasajes terrestres', 'Pasajes terrestres'],
            [128, '3731 Pasajes marítimos, lacustres y fluviales', 'Pasajes marítimos, lacustres y fluviales'],
            [129, '3741 Autotransporte', 'Autotransporte'],
            [130, '3751 Viáticos en el país', 'Viáticos en el país'],
            [131, '3761 Viáticos en el extranjero', 'Viáticos en el extranjero'],
            [132, '3771 Gastos de instalación y traslado de menaje', 'Gastos de instalación y traslado de menaje'],
            [133, '3781 Servicios integrales de traslado y viáticos', 'Servicios integrales de traslado y viáticos'],
            [134, '3791 Otros servicios de traslado y hospedaje', 'Otros servicios de traslado y hospedaje'],
            [135, '3800 Servicios Oficiales', 'Servicios Oficiales'],
            [136, '3811 Gastos de ceremonial', 'Gastos de ceremonial'],
            [137, '3821 Gastos de orden social y cultural', 'Gastos de orden social y cultural'],
            [138, '3831 Congresos y convenciones', 'Congresos y convenciones'],
            [139, '3841 Exposiciones', 'Exposiciones'],
            [140, '3851 Gastos de representación', 'Gastos de representación'],
            [141, '3900 Otros Servicios Generales', 'Otros Servicios Generales'],
            [142, '3911 Servicios funerarios y de cementerios', 'Servicios funerarios y de cementerios'],
            [143, '3921 Impuestos y derechos', 'Impuestos y derechos'],
            [144, '3931 Impuestos y derechos de importación', 'Impuestos y derechos de importación'],
            [145, '3941 Sentencias y resoluciones por autoridad competente', 'Sentencias y resoluciones por autoridad competente'],
            [146, '3951 Penas, multas, accesorios y actualizaciones', 'Penas, multas, accesorios y actualizaciones'],
            [147, '3961 Otros gastos por responsabilidades', 'Otros gastos por responsabilidades'],
            [148, '3971 Utilidades', 'Utilidades'],
            [149, '3981 Impuesto sobre nóminas y otros que se deriven de una relación laboral', 'Impuesto sobre nóminas y otros que se deriven de una relación laboral'],
            [150, '3991 Otros servicios generales', 'Otros servicios generales'],
            [151, '5000 Bienes Muebles, Inmuebles e Intangibles', 'Agrupa las asignaciones para la adquisición de bienes muebles e inmuebles requeridos para el desempeño de las actividades de los entes públicos.'],
            [152, '5100 Mobiliario y Equipo de Administración', 'Mobiliario y Equipo de Administración'],
            [153, '5111 Muebles de oficina y estantería', 'Muebles de oficina y estantería'],
            [154, '5121 Muebles, excepto de oficina y estantería', 'Muebles, excepto de oficina y estantería'],
            [155, '5131 Bienes artísticos, culturales y científicos', 'Bienes artísticos, culturales y científicos'],
            [156, '5141 Objetos de valor', 'Objetos de valor'],
            [157, '5151 Equipo de cómputo y de tecnologías de la información', 'Equipo de cómputo y de tecnologías de la información'],
            [158, '5191 Otros mobiliarios y equipos de administración', 'Otros mobiliarios y equipos de administración'],
            [159, '5200 Mobiliario y Equipo Educacional y Recreativo', 'Mobiliario y Equipo Educacional y Recreativo'],
            [160, '5211 Equipos y aparatos audiovisuales', 'Equipos y aparatos audiovisuales'],
            [161, '5221 Aparatos deportivos', 'Aparatos deportivos'],
            [162, '5231 Cámaras fotográficas y de video', 'Cámaras fotográficas y de video'],
            [163, '5291 Otro mobiliario y equipo educacional y recreativo', 'Otro mobiliario y equipo educacional y recreativo'],
            [164, '5300 Equipo e Instrumental Médico y de Laboratorio', 'Equipo e Instrumental Médico y de Laboratorio'],
            [165, '5311 Equipo médico y de laboratorio', 'Equipo médico y de laboratorio'],
            [166, '5321 Instrumental médico y de laboratorio', 'Instrumental médico y de laboratorio'],
            [167, '5400 Vehículos y Equipo de Transporte', 'Vehículos y Equipo de Transporte'],
            [168, '5411 Vehículos y equipo terrestre', 'Vehículos y equipo terrestre'],
            [169, '5421 Carrocerías y remolques', 'Carrocerías y remolques'],
            [170, '5431 Equipo aeroespacial', 'Equipo aeroespacial'],
            [171, '5441 Equipo ferroviario', 'Equipo ferroviario'],
            [172, '5451 Embarcaciones', 'Embarcaciones'],
            [173, '5491 Otros equipos de transporte', 'Otros equipos de transporte'],
            [174, '5500 Equipo de Defensa y Seguridad', 'Equipo de Defensa y Seguridad'],
            [175, '5511 Equipo de defensa y seguridad', 'Equipo de defensa y seguridad'],
            [176, '5600 Maquinaria, Otros Equipos y Herramientas', 'Maquinaria, Otros Equipos y Herramientas'],
            [177, '5611 Maquinaria y equipo agropecuario', 'Maquinaria y equipo agropecuario'],
            [178, '5621 Maquinaria y equipo industrial', 'Maquinaria y equipo industrial'],
            [179, '5631 Maquinaria y equipo de construcción', 'Maquinaria y equipo de construcción'],
            [180, '5641 Sistemas de aire acondicionado, calefacción y de refrigeración industrial y comercial', 'Sistemas de aire acondicionado, calefacción y de refrigeración industrial y comercial'],
            [181, '5651 Equipo de comunicación y telecomunicación', 'Equipo de comunicación y telecomunicación'],
            [182, '5661 Equipos de generación eléctrica, aparatos y accesorios eléctricos', 'Equipos de generación eléctrica, aparatos y accesorios eléctricos'],
            [183, '5671 Herramientas y máquinas-herramienta', 'Herramientas y máquinas-herramienta'],
            [184, '5691 Otros equipos', 'Otros equipos'],
            [185, '5700 Activos Biológicos', 'Activos Biológicos'],
            [186, '5711 Bovinos', 'Bovinos'],
            [187, '5721 Porcinos', 'Porcinos'],
            [188, '5731 Aves', 'Aves'],
            [189, '5741 Ovinos y caprinos', 'Ovinos y caprinos'],
            [190, '5751 Peces y acuicultura', 'Peces y acuicultura'],
            [191, '5761 Equinos', 'Equinos'],
            [192, '5771 Especies menores y de zoológico', 'Especies menores y de zoológico'],
            [193, '5781 Árboles y plantas', 'Árboles y plantas'],
            [194, '5791 Otros activos biológicos', 'Otros activos biológicos'],
            [195, '5800 Bienes Inmuebles', 'Bienes Inmuebles'],
            [196, '5811 Terrenos', 'Terrenos'],
            [197, '5821 Viviendas', 'Viviendas'],
            [198, '5831 Edificios no residenciales', 'Edificios no residenciales'],
            [199, '5891 Otros bienes inmuebles', 'Otros bienes inmuebles'],
            [200, '5900 Activos Intangibles', 'Activos Intangibles'],
            [201, '5911 Software', 'Software'],
            [202, '5921 Patentes', 'Patentes'],
            [203, '5931 Marcas', 'Marcas'],
            [204, '5941 Derechos', 'Derechos'],
            [205, '5951 Concesiones', 'Concesiones'],
            [206, '5961 Franquicias', 'Franquicias'],
            [207, '5971 Licencias informáticas e intelectuales', 'Licencias informáticas e intelectuales'],
            [208, '5981 Licencias industriales, comerciales y otras', 'Licencias industriales, comerciales y otras'],
            [209, '5991 Otros activos intangibles', 'Otros activos intangibles'],
        ];

        foreach ($clasificaciones as $clasificacion) {
            Clasificacion::updateOrCreate(
                ['id_clasificacion' => $clasificacion[0]],
                [
                    'nombre' => $clasificacion[1],
                    'descripcion' => $clasificacion[2],
                ]
            );
        }
    }
}